### PR TITLE
Feature: drag and drop file selector

### PR DESCRIPTION
**Pull request by marktaiwan**
Allows users to select files by:
- Multiple selections from file dialogue
- Drag and drop files into selection box
- Paste images from clipboard (webkit only)

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
One concern:

1) I try to keep the site in a -somewhat- usable state for users with JavaScript disabled completely. This hides the file input by default and changes the template. In my opinion all of that should be done by the script.

And question:

>Paste images from clipboard (webkit only)
Why only webkit? Are the APIs really that different? I can do http://ie.microsoft.com/testdrive/browser/Editing_Paste_Image/ in Gecko (Firefox), so Gecko seems to support it.
screen shot 2015-03-18 at 5 06 59 pm

**Comment by marktaiwan** [comment]
I understand your concern about keeping the site usable for users that disabled javascript, I'll change it so that the original input element is disabled by default. However, I'm not overly fond of the brief wait for `onready` to kick in, which can be considerable on large threads or a bad connection. Do you have any suggestions as to how to reduce this waiting period?

As for [getting Firefox clipboard image](http://joelb.me/blog/2011/code-snippet-accessing-clipboard-images-with-javascript/), currently the only way of getting clipboard image is to have users paste it into a `contenteditable` element, then grabbing the image from there. For this to work a click event handler is needed to always keep the contenteditable element in focus, and also another function that gets the image after a short delay, since the image will not be immediately available when the paste event is triggered. Afterwards, the image is presented as a data-url, which will need to be converted into a File object before sending.

**Comment by ctrlcctrlv** [comment]
> Edit: would you object to inlining the code that displays the new file selector in the template?
Nope, that's how the CAPTCHA works and is a good method to get it to work. See js/captcha.js and the load_captcha() function. (Also...post.php writes <script>actually_load_captcha</script>...lol)

Also, Firefox's method sounds like a lot of work, hopefully they'll support the WebKit code in a future release. I'm fine with just WebKit support for now.

**Comment by marktaiwan** [comment]
Thanks, it's done.

**Pull request merged**
