### PR TITLE
post-filter

### PR DESCRIPTION
**Pull request by marktaiwan**
###### This is meant as a replacement for `hide-threads.js`, however existing hidden threads will not carry over

Adds a dropdown menu to each post that allows for filtering by:
- post
- post and all replies to it
- poster ID
- poster ID and all replies to it
- name
- tripcode

image

In the options panel, adds a new tab for adding/removing name and
tripcode filters.

image

### CODE REVIEW

**Comment by jeifour** [comment]
Screenshots are looking good.

**Comment by ctrlcctrlv** [comment]
cool, it even keeps track of `new_post` :3

I'm testing it in my user JS a bit, I'll merge into the main codebase after I see if I can find any bugs

Great job as always @marktaiwan

**Comment by ctrlcctrlv** [comment]
few questions:

1. can that menu that comes off of the arrow be easily extended for other features? The post line is getting very visually busy, it might be a good idea to split that into its own script and use it as a generic menu for post actions
2. I think it would be good to also be able to filter Subject and Comment fields. One of the main people that have requested this are those who want to hide all pony threads on /b/, for example. But usually those threads have different OP posts but could always contain "pony" in the subject (or be nicely asked to if they don't already)

Otherwise, I have not found any serious bugs, it looks good :3

**Comment by ctrlcctrlv** [comment]
Oh, by the way, the functions I would add to the menu would be "Report" and "Delete". That script is broken as fuck, needs a rewrite.

**Comment by marktaiwan** [comment]
1. Oh dear, I'm afraid the short answer is no. The addMenu function is written with only the filtering script in mind. However I agree with you that it should be made extensible for other scripts.

2. The actual function wouldn't be too hard to write. But I'm concerned about the UI, the options panel is getting a bit cluttered and will need to be redesigned. And at this point, I think regex filtering should also be supported.

Unfortunately, I'll be away for the next couple of days and won't be able to work on anything.

**Comment by ctrlcctrlv** [comment]
OK. I will merge for now. They are good ideas to keep in mind though. I have wanted to rewrite `fix-report-delete-submit.js` for a while. Maybe when you come back I'll have already done that stuff

**Pull request merged**
