### PR TITLE
Inline expanding: proper data assignment.

### PR DESCRIPTION
**Pull request by marktaiwan**
I forgot how to jQuery

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
lel

**Comment by ctrlcctrlv** [comment]
i fixed this on the site independently without checking github

i put it on the test site but only checked chrome which doesn't refuse to load scripts over a ReferenceError

pretty bad bug here. have to remember to check chrome & FF in future before rebuilding scripts on the site

i thought changes were minimal so it was okay

**Comment by ctrlcctrlv** [comment]
do you use irc or anything @marktaiwan ?

**Comment by marktaiwan** [comment]
I'm afraid not @ctrlcctrlv

**Pull request merged**
