### PR TITLE
fileboard support

### PR DESCRIPTION
**Pull request by czaks**
hi!

at the current time, untested on infinity (tested on vichan) and no settings panel support

enableable using these config options:

    $config['file_board'] = true;
    $config['allowed_tags'] = array('A' => 'Alien swfs', 'C' => 'Chinese cartoon swfs');
    $config['allowed_ext_op'] = array('swf');
    $config['allowed_ext_files'][] = 'swf';
    
    $config['threads_preview'] = 0;
    $config['threads_preview_sticky'] = 0;

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
> no settings panel support

That means only admins can enable it, and I have no idea what Desu (guy who requested this and paid you to do it) would want for tags, or even what board. (Who even owns the /f/ board on 8chan? My stats say "penisboat" and that the board is abandoned...)

If it were up to me I would make everything above exposed in ?/settings. Tags, allowed files, etc...

**Comment by czaks** [comment]
oh also, some jses may break, a working demo (on a vichan board):

https://pl.vichan.net/f/

live-index.js surely breaks, but it isn't present on 8chan.

**Comment by ctrlcctrlv** [comment]
For ?/settings you should make it so they can choose between (checkboxes) .txt, .zip, .7z, .pdf and .swf for fileboards (maybe others?). Please no proprietary archival formats like .rar.

I would only find this fun if you could upload any archive up to 8MB, hehe.

**Comment by ctrlcctrlv** [comment]
btw for ?/settings use `base64_decode` for sanitation because it writes to config.php ( ≖‿≖)
it seems dirty but it has proved safe~

**Comment by czaks** [comment]
Also, some things to consider:

This patch relies on _at least_ one file present. There may be more than one file, just the first one is displayed in index view. ukko will break (not an issue here for now). Spoiler file works. Deleting file... well, sort of works.

**Comment by ctrlcctrlv** [comment]
I see. So fileboards and `$config[require_image_for_op]` are not compatible, latter must always be true.

I also think max_images should be forced to be 1 to be honest.

Deleting file should just erase thread. I'd remove it from mod.php.

**Comment by Jade-Stern** [comment]
This is looking good so far, just needs any of the requests ctrlcctrlv has requested for infinity compatability and a little bit of debug.

Please make files like .webm, .jpg, .png, .gif, etc also available, so board owners can select multiple to be enabled for OP.

**Comment by Jade-Stern** [comment]
Also all op's should be listed on one page, there should be 30 threads tops.
Should just be one page that lists them all

**Comment by czaks** [comment]
Regarding the second, config[max_pages] = 0 should suffice

**Comment by czaks** [comment]
ready and tested

**Pull request merged**
