### PR TITLE
Allow global volunteers to PM users.

### PR DESCRIPTION
**Pull request by guy9000**
Please accept… ;_;

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
woah wrong way to do this, just change the level of `pm_all` to GLOBALVOLUNTEER, that's why i made a new permission

**Comment by guy9000** [comment]
woops :^) one sec

**Comment by ctrlcctrlv** [comment]
right here: https://github.com/ctrlcctrlv/infinity/blob/master/inc/config.php#L1554

this is what needs to change, not the page itself. i'll change it on the server and sync when i join branches again

**Comment by guy9000** [comment]
mmk

**Comment by ctrlcctrlv** [comment]
done, try now

**Pull request merged**
